# Generated by Django 4.2.3 on 2023-07-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
