# Generated by Django 4.2.3 on 2023-09-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
